name = "apple-hk-stock-monitor"
main = "src/index.js"

compatibility_date = "2026-09-20"

workers_dev = true

[triggers]
crons = ["* * * * *"]

[vars]
APPLE_REGION = "HK"
APPLE_LOCALE = "zh-HK"

[secrets]
required = [
  "TELEGRAM_BOT_TOKEN",
  "TELEGRAM_CHAT_ID",
  "ADMIN_KEY"
]

[[d1_databases]]
binding = "DB"
database_name = "apple-stock-monitor"
database_id = "9f20f893-ab31-4ba8-8e58-c786fe36037c"
migrations_dir = "migrations"
